### ISSUE TITLE
Barely readable blog post

### ISSUE THREAD

**Issue by richarson** [AlmaLinux/almalinux.org#10]
Some blog posts have black fonts on dark blue background, making them nearly unreadable.

I checked several blog posts but only saw the issue on this one:

https://almalinux.org/blog/almalinux-8-live-media-beta-now-with-kde-and-xfce/

So, might be a one-time error.

**Comment by richarson** [comment]
BTW: Tested on Opera beta 78.0.4093.103 and Firefox 90.0.2
O.S. is Slackware64 Linux -current (15.0 beta).

**Comment by Addvilz** [comment]
Hi @richarson, thanks for reporting this - these are old posts that were migrated from previous website and some of them still do have pretty ugly artifacts. 

I'll see how we could clean this up. Cheers!

**Comment by Addvilz** [comment]
Actually, never mind, this was due to user error. Fixed.
