### ISSUE TITLE
hugo site lacks responsiveness

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#102]
The next branch hosts the new version of the website built in Hugo, but it lacks responsiveness. Before it can be deployed, the website must be responsive.

**Comment by bennyvasquez** [comment]
@sakelestemur heads up, this is also a problem.

**Comment by codyro** [comment]
I believe this PR was in reference to this issue:

https://github.com/AlmaLinux/almalinux.org/pull/114

**Comment by bennyvasquez** [comment]
Yup! This is resolved now. :)
