### ISSUE TITLE
404 - Missing link licensing-policy

### ISSUE THREAD

**Issue by srbala** [AlmaLinux/almalinux.org#15]
Getting 404 at https://almalinux.org/legal/licensing-policy/

**Comment by Addvilz** [comment]
@srbala any hints where you found this link? This page is at https://almalinux.org/p/the-almalinux-os-licensing-policy/

**Comment by srbala** [comment]
@Addvilz I found it at https://hub.docker.com/_/almalinux page. Thanks for the hint, I can fix the link part documentaion update
