### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by yarons** [AlmaLinux/almalinux.org#17]
Now that Hebrew is fully translated we may need to adjust the design accordingly to display this kind of languages (Persian, Arabic, Urdu, Divehi…) correctly.

**Comment by Addvilz** [comment]
Hmm, your screenshots are in English, not Hebrew - are you sure you have everything up to date? Check out https://almalinux.org/he/ for example.

**Comment by iseletsk** [comment]
My understanding is that RTL support works fine. Please, reopen the ticket if it is still a problem.

![Screen Shot 2022-05-19 at 9 50 47 AM](https://user-images.githubusercontent.com/16657215/169355104-4f551f7a-76b8-4798-ace8-7da76dc6140c.png)
.
