### ISSUE TITLE
Add more information about AlmaLinux  OS available variants

### ISSUE THREAD

**Issue by sboldyreva** [AlmaLinux/almalinux.org#171]
We need to add more information on what AlmaLinux OS variants are available for AlmaLinux users and clients. Currently, there's no such information on the website's main page. 
Here's my proposal

![site-3](https://user-images.githubusercontent.com/87830789/232572187-3c03fb38-7583-4227-a309-9de7d50a08a6.png)

**Comment by bennyvasquez** [comment]
@jaboutboul @jonathanspw @codyro any other ideas/opinions here?

**Comment by jonathanspw** [comment]
I concur that it would be better on a separate page.  What was mentioned in mattermost yesterday was a "downloads" landing page and I think it would be a perfect fit for such a page.

**Comment by codyro** [comment]
I agree with this being the landing for the `Downloads` page. Looking at the front page I feel like we do a good job with vibrant and obvious `Download` call-to-action buttons (floating header is omnipresent, above the fold has a vibrant eye grabbing button, footer has a hyperlink) so there shouldn't be any question to how they get to the download page.

**Comment by sboldyreva** [comment]
Alright, then what about keeping this option while we are working on the full detailed Downloads page?

**Comment by xsub** [comment]
As it was mentioned that Google prefers a dedicated pages with links, I'm fine with incorporating a dedicated landing page. 

However, I also have another idea that could potentially make us want to keep the "Get AlmaLinux OS" section on main page in slightly modified version. And we could keep it despite introducing the new page.

I suggest adding a compact navigation element under the "Get AlmaLinux OS" header, featuring all supported architectures as navigation items.  This is to clearly showcase the supported platforms and add some interactive element to the main page.

Upon selecting an architecture, the download links would update to correspond with the chosen architecture. This can be achieved using a navigation component similar to Bootstrap's .nav:
https://getbootstrap.com/docs/5.0/components/navs-tabs/#horizontal-alignment

Although VuePress doesn't offer a built-in navigation component identical to Bootstrap's .nav, it's possible to develop a custom navigation component utilizing Vue.js and tailor its appearance with CSS.  I can help with this.

Would anybody like to see that?

**Comment by bennyvasquez** [comment]
We're going to put @xsub's suggestion on the back burner for now, but @sboldyreva, please do go forward with building this block for the front page, and then we'll go for a downloads page after we do this in the short term.

**Comment by andrewlukoshko** [comment]
PR is created: https://github.com/AlmaLinux/almalinux.org/pull/178

**Comment by bennyvasquez** [comment]
Gonna close this issue as complete, from 178. Let's start a new one with information about what we want to include on a downloads page.
