### ISSUE TITLE
Existing Open Graph images need update to AlmaLinux 9 installer 

### ISSUE THREAD

**Issue by xsub** [AlmaLinux/almalinux.org#192]
These picture were not updated since AL8 release:
- ./static/images/hero-lg.png
- ./static/images/hero.png

We want them to be current.

**Comment by abuharish02** [comment]
@xsub Hey, As i can see [./static/images/hero-lg.png](https://raw.githubusercontent.com/AlmaLinux/almalinux.org/master/static/images/hero-lg.png)  and  [ ./static/images/hero.png](https://raw.githubusercontent.com/AlmaLinux/almalinux.org/master/static/images/hero.png) both images has ALMALINUX 9.2 written.

**Comment by codyro** [comment]
@xsub fixed these up in https://github.com/AlmaLinux/almalinux.org/pull/197 and they were merged in. Closing this issue as it's fixed at this time :).
