### ISSUE TITLE
Add authors to blog

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#20]
I was thinking about what we can do to help expand the involvement of the community, and some folks really enjoy getting credit when they’re contributing. One way to make it obvious when we have community contributions to the blog would be to add an author name/bio/image to our blog template, and then encourage/invite folks to write blogs about the stuff they’re working on/seeing/whatever in the AlmaLinux/RHEL space.

**Comment by BalramY** [comment]
1) In blog post I am unable to find create method of blog so how blogs are created. Can I also need to add functionality of post blog.
2) where we have page for creating blog by user?

**Comment by iseletsk** [comment]
Please, see https://github.com/AlmaLinux/almalinux.org/issues/19
I think question are related, and it is already covered in #19

**Comment by BalramY** [comment]
I have added fields in admin panel? Can i need to add those fields also in https://almalinux.org/blog/ page?

**Comment by iseletsk** [comment]
I don't think we need this field in admin panel. Whoever is logged in when adding a blog - is the author.
We only need to add it to the blog page.

**Comment by iseletsk** [comment]
In the admin interface click on User profiles, and add an image/name for your (or anyone else) login.
Then change the existing blog and add the author, or when editing a new blog - select the author.
This will make the author show up in the blog section.
