### ISSUE TITLE
Add Membership committee Governance to the website

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#21]
The board has approved the governance for the [membership committee](https://docs.google.com/document/d/1uxc8w6t6OIYM2exT0gjN1-Q7JdfsF10XVh-MqaAXNlo/edit#). Let's get it added to the website! This should look like the [by-laws](https://almalinux.org/p/foundation-bylaws/), and include this at the bottom:

------------------------------
The current membership committee meetings happen every two weeks at 10am Eastern US time. If you have questions for the membership committee, feel free to ask questions in the #membership channel, or reach out to us [directly](mailto:membership@almalinux.org)!!

**Comment by bennyvasquez** [comment]
Yeah, it's not really the goal to try to prevent bad actors from acting bad, so much as allow folks to generally be aware if/when we make changes to the governance. IE: being able to subscribe to the github repo. As an alternative, having the history on web.archive.org at least gives us a historical tracking of it. Having both would be an ideal solution.

**Comment by iseletsk** [comment]
This has been deployed.
