### ISSUE TITLE
Incorporate more details around membership into the website

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#23]
As a board we've crated this document: https://docs.google.com/document/d/12Hx-LUR6CnLkrj1Guq5rzJgKDK4-_y6NjF5ZN-F0_lo/edit 

That content should be incorporated into this page: https://almalinux.org/foundation/members/

**Comment by iseletsk** [comment]
This has been handled in https://github.com/AlmaLinux/almalinux.org/issues/36
