### ISSUE TITLE
Add Slovak language for translation

### ISSUE THREAD

**Issue by shoothub** [AlmaLinux/almalinux.org#24]
Hello,
I'd like to translate Almalinux website to Slovak (sk) language, please add it, so I can start translating it in weblate. I have experiences with translation for projects like Fedora and KDE.

**Comment by shoothub** [comment]
Hello, I requested this a lot of days ago, also from weblate and no response yet. Is this project really have enough resources to support community?

**Comment by shoothub** [comment]
Hi @Addvilz , please check it.

**Comment by Addvilz** [comment]
@shoothub I will look into this as soon as I can, same as with all the other issues.

**Comment by shoothub** [comment]
> 

Thanks.

**Comment by Addvilz** [comment]
Support added.
