### ISSUE TITLE
Ugly picture on facebook if link to blogpost is shared

### ISSUE THREAD

**Issue by lxvd** [AlmaLinux/almalinux.org#26]
If I try to share a link to blog post on Facebook, the post picture looks ugly because it take https://almalinux.org/static/images/logo.svg and cut it from left and right to fit 16x9 frame. As a result, only "lmaL" will remain on picture.

**Comment by bennyvasquez** [comment]
Looks like we should be able to fix this by defining some og tags. Looking through [this guide](https://ordinarycoders.com/blog/article/how-to-add-django-meta-tags) it seems straightforward enough, but I'll defer to @Addvilz or the other contributors here.

**Comment by Addvilz** [comment]
Fixed with 5e2bb533c8a2bc7809bd53d962f95e1ccf5d011c and according to https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Falmalinux.org%2Fblog%2Faws-amis-updated-to-85%2F it should be working fine now.
