### ISSUE TITLE
Set latest packages to default or give users the preference

### ISSUE THREAD

**Issue by pgill98** [AlmaLinux/almalinux.org#27]
Hi!

First off, thanks for all the hard work on AlmaLinux and the super quick updates.

Would it be possible to allow users the ability to set their default module for packages? For example, nginx 1.14 is the default nginx module, however, for certain packages (Phusion Passenger) I need nginx 1.20 to be the default.

Also, if it is set by the repo, would it be possible to make nginx 1.20 the default as nginx 1.14 has been known to have many security vulnerabilities and nginx 1.20 has fixed a lot of those? My team and I have switched over to AlmaLinux 8 as our main production distro from CentOS 7 (because of the EOL). We rely on the nginx 1.20 and Phusion Passenger for our web apps and this new module system has caused some issues in our migration which is why I ask if it is possible to give us the choice for our default module or if you guys could consider setting nginx 1.20 to be the default?

Thanks,
Preet

**Comment by Addvilz** [comment]
@pgill98 it's probably best to ask this in our [chat](https://chat.almalinux.org/almalinux/channels/town-square) or [forums](https://almalinux.discourse.group/). This issue tracker is dedicated to the website.
