### ISSUE TITLE
Update CONTRIBUTING.md with syntax highlighting information

### ISSUE THREAD

**Issue by codyro** [AlmaLinux/almalinux.org#278]
We need to update `CONTRIBUTING.md` with how to utilize syntax highlighting. 

Refs:
* https://gohugo.io/functions/highlight/
* https://gohugo.io/content-management/syntax-highlighting/
* https://github.com/AlmaLinux/almalinux.org/blob/master/content/blog/zenbleed-patch-call-for-testing.md?plain=1#L37-L58

**Comment by codyro** [comment]
After looking at this, I wonder if this is the place to document this.

I have two ideas, but I am open to suggestions:

1. A styling/idiom guide where we can document Hugo specific functions/helpers we use in addition to style preferences for a cleaner code base (EG; tabs vs. spaces, avoid in-line styling, etc.). 

2. Add a styling/idiom section in the `CONTRIBUTING.md` file. 

@jonathanspw @bennyvasquez any idea's?

**Comment by bennyvasquez** [comment]
I think I like the idea of a Styling section in the contributing guide, so there are fewer places to look. I was toying with bringing the contributing guide fully into the README so that it was easier to reference, too.

**Comment by codyro** [comment]
This was fixed in https://github.com/AlmaLinux/almalinux.org/pull/292
