### ISSUE TITLE
Long Links Cause Overflow Allowing Scrolling on Mobile

### ISSUE THREAD

**Issue by mattlasheboro** [AlmaLinux/almalinux.org#279]
**An example of this can be seen here, emulating an iPhone SE:**
https://github.com/AlmaLinux/almalinux.org/assets/10442336/1ded3f7f-044a-45dc-a6f8-0dc8067852ec

**This currently affects this page (and probably more):** 
https://almalinux.org/blog/zenbleed-patch-call-for-testing/

The fix is simple, we just need to add:

```
a {
    overflow-wrap: anywhere;
}
```
To the CSS 

Or if we want to narrow this to only the blog section:
```
.blog-post a {
    overflow-wrap: anywhere;
}
```

Assuming there are no objections I will submit a PR fixing this ASAP.

**Comment by codyro** [comment]
I don't think this would affects anything outside of the blog. Is there any implications of doing it without the `blog-post` class? Could it potentially break some other pages?

**Comment by mattlasheboro** [comment]
@codyro 
I don't think it would break anything on the site.  At worst it would cause a long link to break into multiple lines.

**Comment by codyro** [comment]
Fixed in https://github.com/AlmaLinux/almalinux.org/pull/280
