### ISSUE TITLE
Add Security page to almalinux.org website

### ISSUE THREAD

**Issue by sboldyreva** [AlmaLinux/almalinux.org#289]
We may want to add a Security section and page on our website, that will contain the following links with a short description:

- Errata portal and Errata wiki page
- Errata json files
- OVAL streams
- OpenSCAP guides
- SBOM
- GPG keys

[Adam](https://gitlab.com/sartris) contributes to the project by creating icons for AlmaLinux.

![Image](https://github.com/AlmaLinux/almalinux.org/assets/87830789/919ab87b-0aa7-4c61-9c98-84227b059019)

![Image](https://user-images.githubusercontent.com/87830789/257186103-643016c3-b9d3-4e99-9368-6b7a8baf976b.png)

**Comment by sboldyreva** [comment]
@codyro any ideas, or rephrasings are welcome :) Noted

**Comment by codyro** [comment]
I'm not great with words, so all I came up with was a more generic "Security" heading. Even if you published this as-is, I think it's a massive improvement on what we have :).

**Comment by bennyvasquez** [comment]
I love this and am extremely excited to see it come in, when you can get it built, @sboldyreva!

**Comment by sboldyreva** [comment]
Set of icons from Adam:
![image](https://github.com/AlmaLinux/almalinux.org/assets/87830789/2f05b571-5eff-43df-bd05-244f7bd001e6)

**Comment by sboldyreva** [comment]
@bennyvasquez @codyro if you approve I can prepare a pull request for review

**Comment by bennyvasquez** [comment]
Approved!

**Comment by sboldyreva** [comment]
pull request: 
https://github.com/AlmaLinux/almalinux.org/pull/300

**Comment by codyro** [comment]
Merged in https://github.com/AlmaLinux/almalinux.org/pull/300 :)
