### ISSUE TITLE
Some Images in Blog Section Cause Horizontal Scrolling

### ISSUE THREAD

**Issue by mattlasheboro** [AlmaLinux/almalinux.org#294]
**DESCRIPTION**
Images that are wider than small displays introduce horizontal scrolling.  

**AFFECTED URL(S):**
[https://almalinux.org/blog/building-warpinator-for-almalinux/](https://almalinux.org/blog/building-warpinator-for-almalinux/)
Other URLs are likely affected as well.

**STEPS TO REPRODUCE**
Visit the supplied link on a mobile device.  You can also visit it and use the developer tools to resize the content in a desktop browser.

**PROPOSED FIX**
`.al-page-blog-post article .al-article-content img {
    max-width: 850px;
}`

CHANGE TO

`.al-page-blog-post article .al-article-content img {
    max-width: 100%;
}`

If this was initially added to prevent images from being too wide on large displays we could instead use a media query to apply this only to displays with a viewport width less than 850px.

**Comment by bennyvasquez** [comment]
This seems like a logical solution to me! Want to submit a PR and we'll get it tested before getting it merged in?

**Comment by mattlasheboro** [comment]
Sure thing, I am traveling at the moment but I should be able to get this done this weekend.

**Comment by bennyvasquez** [comment]
resolved.
