### ISSUE TITLE
License issue, terms of service

### ISSUE THREAD

**Issue by comradekingu** [AlmaLinux/almalinux.org#3]
https://almalinux.org/terms-of-service/
>Copyrights
AlmaLinux either owns the intellectual property rights in the text, images audio, video, software, and other content that is made available on this website, or has obtained the permission of the owner of the intellectual property to make it available on this website. **You may not redistribute or copy of any part of this website or its content without prior written permission of AlmaLinux**. You may display on your computer, download and print pages from this website provided: (a) the copyright notice appears on all such printouts, (b) the information will not be altered, (c) the content is only used for personal, educational and non-commercial use, and (d) you do not redistribute or copy the information to any other media. 

This isn't the actual license used, neither here, nor on https://hosted.weblate.org/projects/almalinux/#information

**Comment by Addvilz** [comment]
@comradekingu thanks for bringing this up! 

Just to clarify, the terms of service you are referring to are **for the old website**. This repository contains a different source base entirely and has little to do with that site, and is going to replace that website soon.

I will take note to review this TOS before bringing the new site online, however, I can tell you already that both **the website source code you can find in this repository and translations contributed are MIT licensed, and always will be**.

I will keep this open as a reminder to see about the TOS for the new website and to make sure it reflects above.

**Comment by Addvilz** [comment]
This has been dealt with.

**Comment by comradekingu** [comment]
@Addvilz 
Still needlessly complex, with another clause added now. For some reason the order is what it is,
so that the actual rights come last.
The wiki is not covered AFAICT, which you ask for contributions for
https://wiki.almalinux.org/Contribute.html#help-with-reporting-bugs-and-making-fixes

**Comment by Addvilz** [comment]
@comradekingu not sure what you mean by any of that. What do you suggest should be changed there?

Wiki is out of scope for this repository - it is covered under CC Attribution-ShareAlike 4.0 International https://github.com/AlmaLinux/wiki/blob/master/LICENSE
