### ISSUE TITLE
No content displayed under "AlmaLinux OS in the Press"

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#31]
The homepage has a section "AlmaLinux OS in the Press", but no content is displaying on Chrome or Firefox. The content exists in www/fixtures/press.yaml, but isn't being displayed.

**Comment by Addvilz** [comment]
@bennyvasquez the fixtures are there only for development purposes (local test data), they are not used to seed the real db. This area is managed via admin, and that's where we should add all the press links.

**Comment by Addvilz** [comment]
I'll close this, NTD for code, the content just needs to be created.

**Comment by bennyvasquez** [comment]
I'd like to keep it open. While it might not take code to fix it in this case, we still want to document the need to fix it.

**Comment by jaboutboul** [comment]
Added some blurbs there. Gonna close this for now, but one thing we may want to consider adding is making this a slider/carousel and perhaps including logos of the publications?
