### ISSUE TITLE
add amd certified system

### ISSUE THREAD

**Issue by iseletsk** [AlmaLinux/almalinux.org#43]
Add AMD certified page based on the following mockup, under:
almalinux.org/certified/amd-ryzen-may2022/
[certified.zip](https://github.com/AlmaLinux/almalinux.org/files/8636744/certified.zip)

**Comment by BalramY** [comment]
Can I integrate the same template of mockup or do I need to change its design?

**Comment by iseletsk** [comment]
deployed.
