### ISSUE TITLE
Replace LXD with Incus in the docs

### ISSUE THREAD

**Issue by pastalian** [AlmaLinux/almalinux.org#447]
Image server which AlmaLinux is uploading LXC images - https://images.linuxcontainers.org/ is starting to restrict LXD users. We should encourage our users to use Incus instead of LXD.

Context: https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479

**Comment by codyro** [comment]
We won't be doing this now; however, once Incus is more readily available for AlmaLinux, we can re-evaluate it.

https://github.com/AlmaLinux/almalinux.org/pull/448#issuecomment-2038576801
