### ISSUE TITLE
wiki.almalinux.org provides insufficient/incorrect steps to set up non-default Desktop Environments

### ISSUE THREAD

**Issue by shreyas-malhotra** [AlmaLinux/almalinux.org#466]
Under the "After-installation Guide" present on the wiki, the instructions provided to install non-default Desktop Environments are as follows:

-----------------------------------------------------------------------------------
#### KDE
```
sudo dnf groupinstall "KDE Plasma Workspaces" 
```

#### XFCE
```
sudo dnf groupinstall "Xfce"
```

#### To install Pantheon for AlmaLinux 9:

- Enable EPEL, PowerTools and Synergy repositories
- Install Pantheon Desktop Environment:

```
sudo dnf groupinstall "Pantheon Desktop"
```
-----------------------------------------------------------------------------------

But the package groups for KDE and XFCE mentioned are not listed by dnf prior to setting up third-party repositories, and as such lead to a "Group 'desktop-environment' is not available" message unless EPEL repositories enabled.

Possible solutions: Provision of instructions to enable EPEL repositories prior to the instructions provided to install package groups for KDE and XFCE to avoid confusion among wiki users.

**Comment by codyro** [comment]
Before the above commands are listed, it says to:

> First, enable EPEL and PowerTools/CRB repositories.

Ref: https://wiki.almalinux.org/documentation/after-installation-guide.html#desktop-environment

It could be improved upon by adding the commands to do it (EX, `dnf -y install epel-release`, `crb enable`), though.

If you want to contribute to this page, submit a PR/issue to the Wiki repository [here](https://github.com/almalinux/wiki). This specific page can be found [here](https://github.com/AlmaLinux/wiki/blob/master/docs/documentation/after-installation-guide.md).

**Comment by shreyas-malhotra** [comment]
@codyro Thank you for the guidance, will look into it.
