### ISSUE TITLE
Improve Ryzen certification page

### ISSUE THREAD

**Issue by iseletsk** [AlmaLinux/almalinux.org#51]
1. Please add the word processors to “ The conducted tests ensure that AMD Ryzen™ 5000 series CPUs and, generally for any servers based on Ryzen, XXXXXXXX OS work properly guaranteeing stability, security, and high performance.”  Should read:  “The conducted tests ensure that AMD Ryzen™ XXXX series CPUs and, generally for any servers based on Ryzen processors, XXXXXXXX OS work properly guaranteeing stability, security, and high performance.”

 

2. The block below should be update to look similar to

“Certification for: AMD Ryzen™ 5000 processor series (or 3000 and 5000 processor series). 
![image005](https://user-images.githubusercontent.com/16657215/169840025-cbf122e6-fd06-4de3-981f-a8c580a3d394.png)

3. Is it just the 5000 series or both 5000 and 3000 series of Ryzen supported by OSes? Please pay attention - on the AlmaLinux page it first mentions both the 5000 and 3000 series and then says that the certification is only for the the 5000 series.

 
4. Please change Request system image for test to the plural form (“for tests”) and would also be great to have the system test PDFs available for download
![unnamed (5)](https://user-images.githubusercontent.com/16657215/169840143-02cc5707-9a2d-4a0f-b1a8-2792f4b579dc.png)
3. Change RyzenTM to Ryzen™ in the title of the Almalinux page

4. Vertically align the text and icons on the AlmaLinux page:

![image004](https://user-images.githubusercontent.com/16657215/169840217-7772de88-0f4b-4bb2-9839-f3c82b7c205f.png)

**Comment by BalramY** [comment]
Please provide PDF file so I will attach it.
