### ISSUE TITLE
OG data not working

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#535]
At some point the OG data for blog posts stopped working. 

https://almalinux.org/blog/2024-05-02-introducing-almalinux-hpc-ai-sig/

results in this: 

<img width="815" alt="2024-05-02_12-42-07" src="https://github.com/AlmaLinux/almalinux.org/assets/13630986/8c134245-fe20-456a-ab93-1bca04dabe9b">

Just creating this so we don't forget to take a look at it.

**Comment by codyro** [comment]
It's definitely pulling the default one, let me see if it's something silly real quick.

```html
<meta property="og:image" content="https://almalinux.org/images/newhero.png">
```
