### ISSUE TITLE
There is an "H" instead of an "h" in Shop

### ISSUE THREAD

**Issue by Kirk1984** [AlmaLinux/almalinux.org#56]
Hello,

i have a github account, but thats it with my knowledge about Git so far :)

On the Homepage the link to the Shop ist written "SHop". I guess thats a minor Mistake ;)

**Comment by iseletsk** [comment]
Could you please, provide URL + screenshot. For some reason it shows up as Shop on my screen.

**Comment by jaboutboul** [comment]
Hi @Kirk1984, are you viewing the site in English or another lanaguage?

**Comment by Kirk1984** [comment]
I should have made a screenshot :)

It was on the front page. It was gone hours later.

**Comment by Kirk1984** [comment]
Ah ok. The Site was automativally translated to German for me. On the German translation Shop ist written "SHop"

![Screenshot 2022-06-10 at 09-26-04 AlmaLinux OS - das immerfreie Betriebssystem der Unternehmensklasse](https://user-images.githubusercontent.com/29674972/173013381-79eafa69-3c79-42a6-8c08-79a112ce63cd.png)

**Comment by iseletsk** [comment]
I made a fix in translation, and deploy it a bit later.
