### ISSUE TITLE
Adjust the commercial support display

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#563]
A while ago @sej7278 opened #449 to address how commercial sponsors are presented on the site. While that design suggestion wasn't adopted, the marketing SIG did start discussing the design there, and one of our folks brought up this idea:

<img width="689" alt="2024-05-22_12-08-09" src="https://github.com/AlmaLinux/almalinux.org/assets/13630986/0c8628b8-4fc9-40c7-96bd-50db5887e600">

I think we should adopt it and implement it, for sure. It's a much cleaner look, while remaining consistent with our branding. If we add additional commercial sponsors in the future, we will have to reconsider this display (since I think adding a fourth column here would be cumbersome, though we might be able to make it work), but for now I like it a lot.

**Comment by codyro** [comment]
That is *so much better*.

**Comment by sej7278** [comment]
I like it!

Where do the TuxCare links go, as there's commercial (tech/patch) support as well as commercial and community FIPS packages.

**Comment by bennyvasquez** [comment]
That'd be something that Tuxcare get to define, honestly. I just like the idea of highlighting FIPS more. If they don't have a page that makes the distinction clear, then maybe we make one and push commercial folks to a landing page on their site.

**Comment by sej7278** [comment]
Can we get the TuxCare text changed to:

> TuxCare, a division of CloudLinux Inc., the founding sponsor of the AlmaLinux OS Project, provides tailored support for projects of any complexity. Enhance the performance, security, and reliability of your workloads with extended updates, seamless FIPS compliance, and flexible pay-as-you-go technical support bundles.

And the `Get FIPS` (without "patches") button link pointing to https://tuxcare.com/fips-for-almalinux/

And the `Get Support` button link pointing to https://tuxcare.com/almalinux-enterprise-support/

Please? I don't have the code for the fancy new look or I'd do a proper PR.

**Comment by bennyvasquez** [comment]
@sej7278 just as an FYI: the code doesn't exist yet, which is why you can't do a PR. :D That's just a mockup that was made.

**Comment by sej7278** [comment]
What is outstanding regarding PR #597? It's still in draft it seems.
