### ISSUE TITLE
Add link to the RSS feed on the blog page

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#60]
As a viewer of almalinux.org/blog there's no indication of where to find the [RSS feed](https://almalinux.org/feed/). Let's add a link toward the top of the page on the righthand side (see screenshot with example). If the implementation of the RSS feed allows it, let's include additional options (ie: emails) for notifications of updates as well.

<img width="1341" alt="2022-07-06_10-41-05" src="https://user-images.githubusercontent.com/13630986/177577804-b17afc98-0f35-4691-9ab6-88757c43c1a9.png">

**Comment by iseletsk** [comment]
This has been implemented.
