### ISSUE TITLE
link election page to main almalinux.org page

### ISSUE THREAD

**Issue by iseletsk** [AlmaLinux/almalinux.org#63]
We need to link https://wiki.almalinux.org/Election2022.html to the main almalinux.org page so the election is highly visible.
Maybe a banner?

**Comment by sakelestemur** [comment]
Hi,

A sticky header is created as a demo on CodePen. The sticky header should be implemented at the top of the AlmaLinux official website. 

codepen link: https://codepen.io/pen?template=3cadefe4caf1307aa0df54ec1b10e230

**Comment by bennyvasquez** [comment]
Closing, since this the election is now over (and this was done during the election)
