### ISSUE TITLE
hugo warns

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#631]
I updated my local hugo install and saw these:

```
WARN  DEPRECATED: Kind "taxonomyterm" used in disableKinds is deprecated, use "taxonomy" instead.
WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.
WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.
WARN  deprecated: .Page.PrevPage was deprecated in Hugo v0.123.0 and will be removed in a future release. Use .Page.Prev instead.
WARN  deprecated: .Page.NextPage was deprecated in Hugo v0.123.0 and will be removed in a future release. Use .Page.Next instead.
```

That'll be something we need to address at some point. Honestly not sure how problematic it will be, but theoretically it should be something that someone familiar with hugo can take a look at!

**Comment by Noam-Alum** [comment]
> @Noam-Alum is this something you'd be interested in tackling?

Sure. :grin:

**Comment by Noam-Alum** [comment]
I don't see any drastic changes to the website, I'd love it if one of you guys could verify that.

**Comment by Noam-Alum** [comment]
This issue should be closed. @bennyvasquez 

Right?

**Comment by bennyvasquez** [comment]
yup! Good catch. Thanks, @Noam-Alum!
