### ISSUE TITLE
Update AlmaLinux OS Membership document

### ISSUE THREAD

**Issue by sakelestemur** [AlmaLinux/almalinux.org#67]
Update AlmaLinux OS Membership pdf with the updated version.

The link to update is on https://almalinux.org/foundation/members/ page.

Relevant content: "Membership guidelines are [available here](https://drive.google.com/file/d/1xYkib2FECMoVy5olG9R9audYfGXpOLjf/view?usp=sharing)"

The link to the newest document: https://drive.google.com/file/d/1Z73BBJ5_HY6nMUu3DxnPkFrlXYIpFaQ0/

**Comment by bennyvasquez** [comment]
Closing since this was completed.
