### ISSUE TITLE
Typo on terms of service

### ISSUE THREAD

**Issue by ekohl** [AlmaLinux/almalinux.org#8]
On https://almalinux.org/p/terms-of-service/ there's a typo: `AlmaLinunx` instead of `AlmaLinux`. However, I can't find the terms of service page in this git repository so I can't submit a PR.

**Comment by Addvilz** [comment]
Nice catch, thanks!

TOS is managed from within the CMS, I will update it as soon as possible!

**Comment by ekohl** [comment]
While I have your attention: the trademarks sections states you need prior written consent but not how to get that. Is that done via an email? Which address? I can't find a 'contact us' page.

**Comment by Addvilz** [comment]
@ekohl you might want to talk to Jack about that - jack@almalinux.org

**Comment by iseletsk** [comment]
I think we lost these two pages with new site:
https://almalinux.org/legal/trademark-guidelines/
https://almalinux.org/legal/

It outlined how to get the logo/trademark usage (and no written permission was needed).

**Comment by ekohl** [comment]
Right, that was what I was after. I was going over https://github.com/theforeman/foreman/pull/8498 to make sure we're ok trademark wise in the upcoming release.

**Comment by Addvilz** [comment]
I'll see if I can recover these pages from archive.

**Comment by iseletsk** [comment]
Here are the 3 legal documents that we need to put up on the site (the originals)
https://drive.google.com/drive/folders/1NYR-imizgLRwFh_b351wt77q-NB7KR3D?usp=sharing
Please, tell me if you have any issues accessing them.
