### ISSUE TITLE
Question on best repo for HUGO-based AlmaLinux.org

### ISSUE THREAD

**Issue by sakelestemur** [AlmaLinux/almalinux.org#85]
Hi everyone,
The HUGO-based version of AlmaLinux.org is completed.
What would be the best repo for the HUGO version of the website?

**Comment by bennyvasquez** [comment]
This one is the right place to put it. Create a new PR with the changes, but don't merge it into the primary branch. It'll need a pretty hefty review, and we'll need to see it staged up somewhere. We'll also need to adjust the automated deployment (likely disconnect, and re-implement it). @andrewlukoshko and @jonathanspw can help with that.

**Comment by jonathanspw** [comment]
@sakelestemur let me know when the first copy is ready to test and we'll do initial testing on Cloudflare pages manually.  After that we'll set it up to auto deploy based on PRs.

**Comment by bennyvasquez** [comment]
closing this, as we've resolved where we're going to put the website.
