### ISSUE TITLE
almalinux.org seems to be down

### ISSUE THREAD

**Issue by TonyBostonTB** [AlmaLinux/almalinux.org#9]
I can not ping or surf almalinux.org via IPv4 and ist doesn't seem to have IPv6 Connection anyway

**Comment by Addvilz** [comment]
@TonyBostonTB ping is disabled for the prod host (for some reason). Can you give me some network info, traceroute, or some such?

**Comment by jaboutboul** [comment]
The site was down earlier. It was brought back up and we are investigating the root cause.
