### ISSUE TITLE
Feed is hard to use

### ISSUE THREAD

**Issue by teeks99** [AlmaLinux/almalinux.org#91]
On the blog page, there is a "RSS Feed" button. Clicking it in firefox causes the XML for the RSS to download to my computer...which isn't very useful.

I don't seem to be able to right-click and say "Copy Link" like I can with normal links...which is what I want, so that I can paste it into my RSS reader.

**Comment by bennyvasquez** [comment]
Thanks you, @teeks99! We're in the process of updating the platform behind our website and should be able to fix this after we've changed platforms.

**Comment by jonathanspw** [comment]
This should be more or less sorted now :)
