### ISSUE TITLE
dual scroll bars on "pages" in django

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#93]
PAges that are built manually in Django seem to end up with two scroll bars for some reason. Should be corrected in the new platform, but leaving it here to make sure we test after.
<img width="506" alt="2023-01-04_13-19-27" src="https://user-images.githubusercontent.com/13630986/210623146-08241713-fcaf-4a1f-878e-d3d724ef2275.png">

**Comment by jonathanspw** [comment]
No longer relevant.
